name: AmoCRM Birthday Tasks

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run Python script
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install requests
      run: pip install requests
    - name: Run script
      env:
        AMO_CLIENT_ID: ${{ secrets.AMO_CLIENT_ID }}
        AMO_CLIENT_SECRET: ${{ secrets.AMO_CLIENT_SECRET }}
        AMO_REDIRECT_URI: ${{ secrets.AMO_REDIRECT_URI }}
        AMO_REFRESH_TOKEN: ${{ secrets.AMO_REFRESH_TOKEN }}
        AMO_DOMAIN: ${{ secrets.AMO_DOMAIN }}
      run: python main.py
